### ISSUE TITLE
Tag v0.0.5 missing

### ISSUE THREAD

**Issue by jayvdb** [moremoban/yehua#13]

**Comment by chfw** [comment]
sigh.. hence I mistakenly released 0.0.5 tag again.

**Comment by jayvdb** [comment]
Does [the changelog](https://github.com/moremoban/yehua/blob/dev/CHANGELOG.rst) reflect what was in the PyPI releases?

If so, this can be closed.

**Comment by chfw** [comment]
Yes. Hence closing. Will put both in sync in the future
