### ISSUE TITLE
Python 2

### ISSUE THREAD

**Issue by jayvdb** [moremoban/yehua#26]
As a CLI program, there should be no users who depend on this as a library, and everyone should be using primarily Python 3 now, so Python 2 runtime support can be dropped.

However it still should be able to generate Python 2 compatible code (Python 2 usage is still quite high), so it would be useful for py2 jobs to keep running in order to check the generated output.  At least AppVeyor has both py2 and py3 on the same image, so Python 3 could be used to generate, and then py2 used to check the generated output.

**Comment by chfw** [comment]
Sounds good.

When moban 0.7.x will come, yehua’s python 2 support will be affected.

**Comment by chfw** [comment]
The generation of python 2 code is an attribute of pypi-mobans. Hence yehua 0.1.0 will proceed to drop python 2 support.
