### ISSUE TITLE
setup.py should provide an extra which suggests installation of pypi-mobans-pkg

### ISSUE THREAD

**Issue by jayvdb** [moremoban/yehua#32]
`pypi-mobans-pkg` is almost a requirement (most users are unlikely to create their own template sets), but moban supports installing template packages dynamically on demand.

However the user may want to pre-install all dependencies using `pip`, and not need to use the internet after that in order to use yehua.
.
And when they upgrade yehua, they will expect that the templates will also have been updated if yehua needs a new version of the templates.

One way to achieve this is to add an extra, e.g. called `templates`, which specifies any necessary moban template packages with the appropriate versions.

This also helps distro packagers, as they will see the version changes occurring in setup.py , but they will ignore a version appearing in a yaml file deep inside the package.

**Comment by jayvdb** [comment]
Also another trick to help distro packages is to add a test which needs the required version of `pypi-mobans-pkg`, so then they need to update the `pypi-mobans-pkg` package before the tests of yehua will pass.

**Comment by chfw** [comment]
Yep, offline use case was ignored but can be supported like what you laid out.
