### ISSUE TITLE
Non-verbose mode as default

### ISSUE THREAD

**Issue by jayvdb** [moremoban/yehua#38]
The yehua output contains:

```
Requirement already satisfied: pypi-mobans-pkg==0.0.7 in /home/python3.7/lib/python3.7/site-packages (0.0.7)
Requirement already satisfied: lml in /home/python3.7/lib/python3.7/site-packages (from pypi-mobans-pkg==0.0.7) (0.0.9)
```

IMO that is unnecessary except in a verbose mode, which shouldnt be default.

Also I dont see how it is beneficial for a moban template pkg to include `lml` , as moban already depends on it, so it should already exist..?

**Comment by chfw** [comment]
With hindsight, it should not depend on lml

**Comment by jayvdb** [comment]
Also I see `Warning: 'requires' is deprecated since 0.6.0! Please use pypi:// or git:// notation instead` , but I think I am using the latest yehua and moban and pypi-moban-pkg.
Something somewhere must be using old syntax...?

**Comment by chfw** [comment]
Yes, moban file needs updating

**Comment by chfw** [comment]
the following legacy code exists in the library. That's why lml was listed. With pypifs, lml related code shall exist the stage. 

```
# flake8: noqa
import os
from pypi_mobans_pkg._version import __version__
from pypi_mobans_pkg._version import __author__
from lml.plugin import PluginInfo


@PluginInfo('library', tags=['setupmobans', 'pypi', 'pypi-mobans-pkg'])
class Pypkg():
    def __init__(self):
        __package_path__ = os.path.dirname(__file__)
        self.resources_path = os.path.join(
            __package_path__, "resources")
```

the only plus point is: pypi-mobans-pkg will support older version of moban < 0.6.0.

**Comment by chfw** [comment]
above code has been removed in pypi-moban-pkg 0.0.13, so such legacy use is gone forever.

https://travis-ci.org/github/moremoban/moban/jobs/682686615
