### ISSUE TITLE
Validate license

### ISSUE THREAD

**Issue by jayvdb** [moremoban/yehua#40]
`license: MIT2` is accepted as valid.

The license should be a value that is SPDX compliant, using one of https://pypi.org/search/?q=spdx to validate it.

Creating valid LICENSE files is a bit hard, as a new template syntax is needed to match the spdx files or match the https://github.com/github/choosealicense.com/ files.  c.f. https://pypi.org/search/?q=spdx

**Comment by jayvdb** [comment]
cookiecutter templates usually use a select list for this.

**Comment by chfw** [comment]
Select list is done since 0.1.0

Additional license can be added separately.
