### ISSUE TITLE
Clarify copyright owner and prefill/fallback with author

### ISSUE THREAD

**Issue by jayvdb** [moremoban/yehua#42]
Most users will be OSS devs who are their own copyright owner.

It will be a bit unexpected that it is stored in a yaml field called `company`.

I suggest the UI labels the field "Company/copyright owner", and the templates detect when it is empty, and to use the authors name instead.

**Comment by chfw** [comment]
https://github.com/moremoban/yehua/blob/dev/yehua/resources/yehua.yml

Supported since 0.1.1
